input_text = """
Subject: You're Invited: Annual Product Launch Event

Hi Team,

Join us for our Annual Product Launch Event!

Date: Friday, April 12th, 2025
Time: 2:00 PM - 5:00 PM Pacific Time
Location: The Grand Ballroom at Hyatt Regency, 5 Embarcadero Center, San Francisco, CA 94111
Virtual option: https://stream.company.io/product-launch-2025

Agenda:
- 2:00 PM: Registration and Welcome Reception
- 2:30 PM: CEO Keynote by Amanda Rodriguez
- 3:15 PM: Product Demos and Breakout Sessions
- 4:15 PM: Panel Q&A with Product Team
- 4:45 PM: Networking and Cocktail Hour

Please RSVP by April 5th to events@company.io. Space limited to 300 in-person attendees.

Dress code: Business casual
Parking: Valet parking available

Best regards,
Maria Chen
VP of Marketing
maria.chen@company.io
(415) 555-7890
"""

expected_json = """{
  "event_name": "Annual Product Launch Event",
  "event_type": "presentation",
  "date_time": {
    "start_date": "2025-04-12",
    "start_time": "2:00 PM",
    "end_time": "5:00 PM",
    "timezone": "PST",
    "all_day": false
  },
  "location": {
    "type": "hybrid",
    "venue_name": "Hyatt Regency",
    "address": "5 Embarcadero Center, San Francisco, CA 94111",
    "room": "The Grand Ballroom",
    "virtual_link": "https://stream.company.io/product-launch-2025"
  },
  "organizer": {
    "name": "Maria Chen",
    "email": "maria.chen@company.io",
    "phone": "(415) 555-7890",
    "organization": "VP of Marketing"
  },
  "attendees": [
    {
      "name": "Amanda Rodriguez",
      "role": "speaker"
    }
  ],
  "agenda": [
    {
      "time": "2:00 PM",
      "topic": "Registration and Welcome Reception"
    },
    {
      "time": "2:30 PM",
      "topic": "CEO Keynote",
      "speaker": "Amanda Rodriguez"
    },
    {
      "time": "3:15 PM",
      "topic": "Product Demos and Breakout Sessions"
    },
    {
      "time": "4:15 PM",
      "topic": "Panel Q&A with Product Team"
    },
    {
      "time": "4:45 PM",
      "topic": "Networking and Cocktail Hour"
    }
  ],
  "registration": {
    "capacity": 300
  },
  "rsvp": {
    "required": true,
    "deadline": "2025-04-05",
    "contact": "events@company.io"
  },
  "special_instructions": "Business casual dress code. Valet parking available."
}"""
