input_text = """
TECH CAREER FAIR 2025
Connect with Top Technology Employers!

📅 Saturday, May 10, 2025 | 10:00 AM - 4:00 PM
📍 City Convention Center, Hall A & B
   123 Convention Way, Austin, TX 78701

FEATURED COMPANIES:
Google • Microsoft • Amazon • Apple • Tesla • Meta • IBM • Oracle • + 50 more!

SCHEDULE:
10:00 AM - Doors Open & Registration
10:30 AM - Welcome Presentation (Main Stage)
11:00 AM - Company Booths Open / Resume Reviews
12:30 PM - Panel: "Breaking Into Tech" (Room 201)
2:00 PM - Workshop: "Ace Your Technical Interview" (Room 202)
3:30 PM - Raffle Drawing (Main Stage)

REGISTRATION: FREE but required
Sign up at: www.techcareerfair.com/register
Early bird deadline: April 25th (free t-shirt!)

Parking: Convention Center Garage ($10 all-day)

QUESTIONS?
Email: info@techcareerfair.com
Call: (512) 555-JOBS

Organized by Austin Tech Alliance & Career Services
"""

expected_json = """{
  "event_name": "Tech Career Fair 2025",
  "event_type": "networking",
  "date_time": {
    "start_date": "2025-05-10",
    "start_time": "10:00 AM",
    "end_time": "4:00 PM",
    "all_day": false
  },
  "location": {
    "type": "physical",
    "venue_name": "City Convention Center",
    "address": "123 Convention Way, Austin, TX 78701",
    "room": "Hall A & B"
  },
  "organizer": {
    "name": "Austin Tech Alliance & Career Services",
    "email": "info@techcareerfair.com",
    "phone": "(512) 555-JOBS"
  },
  "description": "Career fair connecting job seekers with top technology employers including Google, Microsoft, Amazon, Apple, Tesla, Meta, IBM, Oracle, and 50+ more companies",
  "agenda": [
    {
      "time": "10:00 AM",
      "topic": "Doors Open & Registration"
    },
    {
      "time": "10:30 AM",
      "topic": "Welcome Presentation"
    },
    {
      "time": "11:00 AM",
      "topic": "Company Booths Open / Resume Reviews"
    },
    {
      "time": "12:30 PM",
      "topic": "Breaking Into Tech"
    },
    {
      "time": "2:00 PM",
      "topic": "Ace Your Technical Interview"
    },
    {
      "time": "3:30 PM",
      "topic": "Raffle Drawing"
    }
  ],
  "registration": {
    "required": true,
    "deadline": "2025-04-25",
    "link": "www.techcareerfair.com/register",
    "fee": "Free"
  },
  "tags": ["career", "technology", "networking"]
}"""
