input_text = """
KUBERNETES WORKSHOP FÜR EINSTEIGER

Samstag, 5. April 2025 | 10:00 - 16:00 Uhr (MESZ)
IT-Campus München, Schulungsraum 2B
Leopoldstraße 45, 80802 München

Dozent: Stefan Becker (stefan.becker@devacademy.de)
15 Jahre Erfahrung in Cloud-Native-Technologien

Inhalte:
10:00-10:45 Einführung in Container-Orchestrierung
10:45-12:00 Kubernetes Grundlagen (Hands-on)
12:00-13:00 Mittagspause
13:00-14:30 Pods, Services und Deployments
14:30-14:45 Pause
14:45-16:00 Best Practices und Live-Demo

Teilnahmegebühr: 199 € (inkl. Mittagessen und Getränke)
Max. 15 Teilnehmer

Anmeldung bis 28. März: https://devacademy.de/kubernetes-workshop

Voraussetzungen: Docker-Grundkenntnisse, eigener Laptop
Setup-Anleitung: https://devacademy.de/k8s-setup.pdf

DevAcademy GmbH
workshops@devacademy.de | +49 89 9876543
"""

expected_json = """{
  "event_name": "Kubernetes Workshop für Einsteiger",
  "event_type": "workshop",
  "date_time": {
    "start_date": "2025-04-05",
    "start_time": "10:00 AM",
    "end_time": "4:00 PM",
    "timezone": "MESZ",
    "all_day": false
  },
  "location": {
    "type": "physical",
    "venue_name": "IT-Campus München",
    "address": "Leopoldstraße 45, 80802 München",
    "room": "Schulungsraum 2B"
  },
  "organizer": {
    "name": "DevAcademy GmbH",
    "email": "workshops@devacademy.de",
    "phone": "+49 89 9876543"
  },
  "attendees": [
    {
      "name": "Stefan Becker",
      "email": "stefan.becker@devacademy.de",
      "role": "speaker"
    }
  ],
  "agenda": [
    {
      "time": "10:00 AM",
      "topic": "Einführung in Container-Orchestrierung",
      "duration": "45 min"
    },
    {
      "time": "10:45 AM",
      "topic": "Kubernetes Grundlagen (Hands-on)",
      "duration": "75 min"
    },
    {
      "time": "12:00 PM",
      "topic": "Mittagspause",
      "duration": "60 min"
    },
    {
      "time": "1:00 PM",
      "topic": "Pods, Services und Deployments",
      "duration": "90 min"
    },
    {
      "time": "2:30 PM",
      "topic": "Pause",
      "duration": "15 min"
    },
    {
      "time": "2:45 PM",
      "topic": "Best Practices und Live-Demo",
      "duration": "75 min"
    }
  ],
  "registration": {
    "required": true,
    "deadline": "2025-03-28",
    "link": "https://devacademy.de/kubernetes-workshop",
    "fee": "199 €",
    "capacity": 15
  },
  "attachments": [
    {
      "name": "Setup-Anleitung",
      "url": "https://devacademy.de/k8s-setup.pdf",
      "type": "handout"
    }
  ],
  "tags": ["kubernetes", "cloud-native", "hands-on"],
  "special_instructions": "Docker-Grundkenntnisse erforderlich. Eigener Laptop mitbringen. Mittagessen und Getränke inklusive."
}"""
