input_text = """
DIGITALE TRANSFORMATION KONFERENZ 2025

3-tägige Fachkonferenz für Führungskräfte

16. - 18. Juni 2025
Messe Frankfurt, Halle 3
Ludwig-Erhard-Anlage 1, 60327 Frankfurt am Main

Keynote-Speaker:
• Prof. Dr. Anna Schneider (TU München) - "Digitalisierung im Mittelstand"
• Dr. Michael Wagner (SAP) - "KI-gestützte Geschäftsprozesse"
• Julia Krause (McKinsey) - "Change Management 4.0"

Programm-Highlights:
Tag 1: Digitale Geschäftsmodelle
Tag 2: Cloud & Infrastruktur, Cybersecurity
Tag 3: Innovation & Future Trends

300+ Teilnehmer erwartet | 40+ Vorträge | Networking-Abend am ersten Tag

Frühbucher (bis 15. Mai): 899 € | Regulär: 1.199 €

Anmeldung: https://digital-transformation.de/konferenz
Kontakt: info@digital-transformation.de | +49 69 12345678

Veranstalter: Deutsche Digitalisierungs-Initiative e.V.
"""

expected_json = """{
  "event_name": "Digitale Transformation Konferenz 2025",
  "event_type": "conference",
  "date_time": {
    "start_date": "2025-06-16",
    "end_date": "2025-06-18",
    "all_day": false
  },
  "location": {
    "type": "physical",
    "venue_name": "Messe Frankfurt",
    "address": "Ludwig-Erhard-Anlage 1, 60327 Frankfurt am Main",
    "room": "Halle 3"
  },
  "organizer": {
    "name": "Deutsche Digitalisierungs-Initiative e.V.",
    "email": "info@digital-transformation.de",
    "phone": "+49 69 12345678"
  },
  "attendees": [
    {
      "name": "Prof. Dr. Anna Schneider",
      "role": "keynote speaker"
    },
    {
      "name": "Dr. Michael Wagner",
      "role": "keynote speaker"
    },
    {
      "name": "Julia Krause",
      "role": "keynote speaker"
    }
  ],
  "description": "3-tägige Fachkonferenz für Führungskräfte zum Thema digitale Transformation",
  "registration": {
    "required": true,
    "deadline": "2025-05-15",
    "link": "https://digital-transformation.de/konferenz",
    "fee": "Frühbucher: 899 €, Regulär: 1.199 €",
    "capacity": 300
  },
  "tags": ["digitalisierung", "transformation", "führungskräfte"]
}"""
