input_text = """
MITARBEITER-SCHULUNG: DATENSCHUTZ UND DSGVO

Montag, 28. April 2025
9:00 - 13:00 Uhr (MESZ)

Standort: Hauptverwaltung, Schulungsraum 1. OG
Karlsplatz 12, 80335 München
Online-Teilnahme: https://teams.microsoft.com/schulung-dsgvo
Meeting-ID: 987-654-321

Referent: Rechtsanwalt Dr. Peter Müller (Datenschutzbeauftragter)
Assistenz: Sandra Wagner (Compliance-Team)

Ablauf:
09:00 - Einführung und Begrüßung (Dr. Müller)
09:15 - Grundlagen DSGVO (60 Min)
10:15 - Kaffeepause (15 Min)
10:30 - Praktische Anwendung im Unternehmen (90 Min)
12:00 - Mittagspause (30 Min)
12:30 - Fallbeispiele und Diskussion (30 Min)

Pflichtveranstaltung für alle Mitarbeiter mit Datenzugriff

Anmeldung bis 21. April: hr@unternehmen.de

Unterlagen:
- DSGVO-Handbuch: https://intranet.unternehmen.de/dsgvo-handbuch.pdf
- Checkliste: https://intranet.unternehmen.de/checkliste.pdf

Personalabteilung
hr@unternehmen.de | +49 89 55566677
"""

expected_json = """{
  "event_name": "Mitarbeiter-Schulung: Datenschutz und DSGVO",
  "event_type": "training",
  "date_time": {
    "start_date": "2025-04-28",
    "start_time": "9:00 AM",
    "end_time": "1:00 PM",
    "timezone": "MESZ",
    "all_day": false
  },
  "location": {
    "type": "hybrid",
    "venue_name": "Hauptverwaltung",
    "address": "Karlsplatz 12, 80335 München",
    "room": "Schulungsraum 1. OG",
    "virtual_link": "https://teams.microsoft.com/schulung-dsgvo",
    "meeting_id": "987-654-321"
  },
  "organizer": {
    "name": "Personalabteilung",
    "email": "hr@unternehmen.de",
    "phone": "+49 89 55566677"
  },
  "attendees": [
    {
      "name": "Dr. Peter Müller",
      "role": "speaker",
      "required": true
    },
    {
      "name": "Sandra Wagner",
      "role": "moderator"
    }
  ],
  "agenda": [
    {
      "time": "9:00 AM",
      "topic": "Einführung und Begrüßung",
      "speaker": "Dr. Müller"
    },
    {
      "time": "9:15 AM",
      "topic": "Grundlagen DSGVO",
      "duration": "60 min"
    },
    {
      "time": "10:15 AM",
      "topic": "Kaffeepause",
      "duration": "15 min"
    },
    {
      "time": "10:30 AM",
      "topic": "Praktische Anwendung im Unternehmen",
      "duration": "90 min"
    },
    {
      "time": "12:00 PM",
      "topic": "Mittagspause",
      "duration": "30 min"
    },
    {
      "time": "12:30 PM",
      "topic": "Fallbeispiele und Diskussion",
      "duration": "30 min"
    }
  ],
  "registration": {
    "required": true,
    "deadline": "2025-04-21"
  },
  "attachments": [
    {
      "name": "DSGVO-Handbuch",
      "url": "https://intranet.unternehmen.de/dsgvo-handbuch.pdf",
      "type": "handout"
    },
    {
      "name": "Checkliste",
      "url": "https://intranet.unternehmen.de/checkliste.pdf",
      "type": "handout"
    }
  ],
  "tags": ["training", "datenschutz", "dsgvo", "pflicht"],
  "special_instructions": "Pflichtveranstaltung für alle Mitarbeiter mit Datenzugriff"
}"""
