input_text = """
NEW EMPLOYEE ONBOARDING
Human Resources Department

Monday, February 3, 2025
9:00 AM - 3:00 PM EST

Location: Corporate Headquarters, Training Center A
500 Main Street, New York, NY 10001
Virtual: https://meet.company.com/onboarding-feb (Code: 456-789-012)

Schedule:
9:00-9:45 Welcome & Company Overview (Jennifer White, HR Director)
9:45-10:45 HR Policies and Benefits (Jennifer White)
10:45-11:00 Break
11:00-12:30 IT Systems Setup (David Lee, IT Manager)
12:30-1:30 Team Lunch
1:30-2:30 Department Introductions
2:30-3:00 Q&A and Next Steps (Jennifer White)

Before you arrive:
✓ Complete pre-onboarding paperwork
✓ Bring government-issued ID for badge

Materials:
- Employee Handbook: https://intranet.company.com/handbook.pdf
- System Access Form: https://intranet.company.com/access-form.pdf

Questions? hr@company.com
"""

expected_json = """{
  "event_name": "New Employee Onboarding",
  "event_type": "training",
  "date_time": {
    "start_date": "2025-02-03",
    "start_time": "9:00 AM",
    "end_time": "3:00 PM",
    "timezone": "EST",
    "all_day": false
  },
  "location": {
    "type": "hybrid",
    "venue_name": "Corporate Headquarters",
    "address": "500 Main Street, New York, NY 10001",
    "room": "Training Center A",
    "virtual_link": "https://meet.company.com/onboarding-feb",
    "meeting_id": "456-789-012"
  },
  "organizer": {
    "name": "Human Resources",
    "email": "hr@company.com",
    "organization": "HR Department"
  },
  "attendees": [
    {
      "name": "Jennifer White",
      "role": "speaker"
    },
    {
      "name": "David Lee",
      "role": "speaker"
    }
  ],
  "agenda": [
    {
      "time": "9:00 AM",
      "topic": "Welcome & Company Overview",
      "speaker": "Jennifer White",
      "duration": "45 min"
    },
    {
      "time": "9:45 AM",
      "topic": "HR Policies and Benefits",
      "speaker": "Jennifer White",
      "duration": "60 min"
    },
    {
      "time": "10:45 AM",
      "topic": "Break",
      "duration": "15 min"
    },
    {
      "time": "11:00 AM",
      "topic": "IT Systems Setup",
      "speaker": "David Lee",
      "duration": "90 min"
    },
    {
      "time": "12:30 PM",
      "topic": "Team Lunch",
      "duration": "60 min"
    },
    {
      "time": "1:30 PM",
      "topic": "Department Introductions",
      "duration": "60 min"
    },
    {
      "time": "2:30 PM",
      "topic": "Q&A and Next Steps",
      "speaker": "Jennifer White",
      "duration": "30 min"
    }
  ],
  "attachments": [
    {
      "name": "Employee Handbook",
      "url": "https://intranet.company.com/handbook.pdf",
      "type": "handout"
    },
    {
      "name": "System Access Form",
      "url": "https://intranet.company.com/access-form.pdf",
      "type": "handout"
    }
  ],
  "tags": ["onboarding", "training", "hr"],
  "special_instructions": "Complete pre-onboarding paperwork before the session. Bring government-issued ID for badge."
}"""
