input_text = """
HANDS-ON DOCKER WORKSHOP
DevOps Training GmbH

Friday, February 28, 2025 | 9:00 AM - 4:00 PM CET
Tech Hub Berlin, Training Room 3
Alexanderplatz 7, 10178 Berlin, Germany

Instructor: Marcus Schmidt (m.schmidt@devopstraining.de)

Schedule:
09:00-09:45 Introduction to Containers
09:45-11:15 Docker Basics - Hands-on Lab
11:15-11:30 Coffee Break
11:30-13:00 Docker Compose and Multi-container Apps
13:00-14:00 Lunch Break
14:00-15:30 Best Practices and Production Deployment
15:30-16:00 Final Project and Q&A

Price: €299 | Max 20 participants
Register by February 20: https://devopstraining.de/workshops/docker

Prerequisites: Basic command line knowledge
Requirements: Laptop with Docker Desktop installed

Downloads:
- Prerequisites guide: https://devopstraining.de/docker-prereqs.pdf
- Lab setup: https://devopstraining.de/docker-setup.pdf

Contact: workshops@devopstraining.de | +49-30-555-0123
"""

expected_json = """{
  "event_name": "Hands-on Docker Workshop",
  "event_type": "workshop",
  "date_time": {
    "start_date": "2025-02-28",
    "start_time": "9:00 AM",
    "end_time": "4:00 PM",
    "timezone": "CET",
    "all_day": false
  },
  "location": {
    "type": "physical",
    "venue_name": "Tech Hub Berlin",
    "address": "Alexanderplatz 7, 10178 Berlin, Germany",
    "room": "Training Room 3"
  },
  "organizer": {
    "name": "DevOps Training GmbH",
    "email": "workshops@devopstraining.de",
    "phone": "+49-30-555-0123"
  },
  "attendees": [
    {
      "name": "Marcus Schmidt",
      "email": "m.schmidt@devopstraining.de",
      "role": "speaker"
    }
  ],
  "agenda": [
    {
      "time": "9:00 AM",
      "topic": "Introduction to Containers",
      "duration": "45 min"
    },
    {
      "time": "9:45 AM",
      "topic": "Docker Basics - Hands-on Lab",
      "duration": "90 min"
    },
    {
      "time": "11:15 AM",
      "topic": "Coffee Break",
      "duration": "15 min"
    },
    {
      "time": "11:30 AM",
      "topic": "Docker Compose and Multi-container Apps",
      "duration": "90 min"
    },
    {
      "time": "1:00 PM",
      "topic": "Lunch Break",
      "duration": "60 min"
    },
    {
      "time": "2:00 PM",
      "topic": "Best Practices and Production Deployment",
      "duration": "90 min"
    },
    {
      "time": "3:30 PM",
      "topic": "Final Project and Q&A",
      "duration": "30 min"
    }
  ],
  "registration": {
    "required": true,
    "deadline": "2025-02-20",
    "link": "https://devopstraining.de/workshops/docker",
    "fee": "€299",
    "capacity": 20
  },
  "attachments": [
    {
      "name": "Prerequisites guide",
      "url": "https://devopstraining.de/docker-prereqs.pdf",
      "type": "handout"
    },
    {
      "name": "Lab setup",
      "url": "https://devopstraining.de/docker-setup.pdf",
      "type": "handout"
    }
  ],
  "tags": ["docker", "devops", "hands-on"],
  "special_instructions": "Basic command line knowledge required. Laptop with Docker Desktop pre-installed."
}"""
