input_text = """
Contact Information Form

First Name: Jennifer
Middle Initial: L
Last Name: Rodriguez
Title: Dr.

Position: Director of Research
Company: BioTech Innovations
Department: Clinical Trials

Primary Email: jrodriguez@biotech-innovations.com
Secondary Email: jenny.rodriguez@university.edu

Mobile Phone: 555-345-6789
Work Phone: 555-987-6543 (extension 205)
Home Phone: 555-456-7890

Work Address:
789 Research Park Drive
Building C, Floor 3
Boston, MA 02115
United States

Mailing Address:
Same as work address

Website: www.biotechinnovations.com/team/jrodriguez
LinkedIn: www.linkedin.com/in/jennifer-rodriguez-phd
Twitter: @DrJenRodriguez

Time Zone: Eastern (ET)
Preferred Contact Method: Email
Languages Spoken: English, Spanish

Assistant Information:
Name: Patricia Kim
Email: pkim@biotech-innovations.com
Phone: 555-987-6543 ext. 201
"""

expected_json = """{
  "name": {
    "full_name": "Dr. Jennifer L Rodriguez",
    "first_name": "Jennifer",
    "middle_name": "L",
    "last_name": "Rodriguez",
    "prefix": "Dr."
  },
  "job_title": "Director of Research",
  "company": {
    "name": "BioTech Innovations",
    "department": "Clinical Trials"
  },
  "email_addresses": [
    {
      "email": "jrodriguez@biotech-innovations.com",
      "type": "work",
      "primary": true
    },
    {
      "email": "jenny.rodriguez@university.edu",
      "type": "other"
    }
  ],
  "phone_numbers": [
    {
      "number": "555-345-6789",
      "type": "mobile",
      "primary": true
    },
    {
      "number": "555-987-6543",
      "type": "work",
      "extension": "205"
    },
    {
      "number": "555-456-7890",
      "type": "home"
    }
  ],
  "addresses": [
    {
      "type": "work",
      "street": "789 Research Park Drive, Building C, Floor 3",
      "city": "Boston",
      "state": "MA",
      "postal_code": "02115",
      "country": "United States",
      "full_address": "789 Research Park Drive, Building C, Floor 3, Boston, MA 02115, United States"
    }
  ],
  "websites": [
    {
      "url": "www.biotechinnovations.com/team/jrodriguez",
      "type": "company"
    }
  ],
  "social_media": {
    "linkedin": "www.linkedin.com/in/jennifer-rodriguez-phd",
    "twitter": "@DrJenRodriguez"
  },
  "preferred_contact_method": "email",
  "timezone": "ET",
  "language": "English",
  "assistant": {
    "name": "Patricia Kim",
    "email": "pkim@biotech-innovations.com",
    "phone": "555-987-6543 ext. 201"
  }
}"""
