input_text = """
Robert Chen
Chief Executive Officer
Apex Financial Services

For all meeting requests and inquiries, please contact my assistant:

Executive Assistant: Maria Garcia
Direct Line: (555) 789-0123
Email: m.garcia@apexfinancial.com

Robert Chen - Direct Contact (Urgent Only):
Mobile: (555) 321-9876
Email: r.chen@apexfinancial.com

Corporate Headquarters:
4500 Park Avenue, 28th Floor
New York, NY 10022

Board Member: Tech Innovation Foundation
Advisory Role: StartupAccelerator NYC

LinkedIn: linkedin.com/in/robertchen-ceo
"""

expected_json = """{
  "name": {
    "full_name": "Robert Chen",
    "first_name": "Robert",
    "last_name": "Chen"
  },
  "job_title": "Chief Executive Officer",
  "company": {
    "name": "Apex Financial Services"
  },
  "email_addresses": [
    {
      "email": "r.chen@apexfinancial.com",
      "type": "work",
      "primary": true
    }
  ],
  "phone_numbers": [
    {
      "number": "(555) 321-9876",
      "type": "mobile",
      "primary": true
    }
  ],
  "addresses": [
    {
      "type": "work",
      "street": "4500 Park Avenue, 28th Floor",
      "city": "New York",
      "state": "NY",
      "postal_code": "10022",
      "full_address": "4500 Park Avenue, 28th Floor, New York, NY 10022"
    }
  ],
  "social_media": {
    "linkedin": "linkedin.com/in/robertchen-ceo"
  },
  "assistant": {
    "name": "Maria Garcia",
    "email": "m.garcia@apexfinancial.com",
    "phone": "(555) 789-0123"
  },
  "notes": "Board Member: Tech Innovation Foundation, Advisory Role: StartupAccelerator NYC. Contact assistant for meeting requests."
}"""
