input_text = """
名前: 田中 太郎 (Tanaka Taro)
役職: アジア太平洋地域マネージャー
会社: グローバルテック株式会社

Email (work): t.tanaka@globaltech.co.jp
Email (personal): taro.tanaka@example.com

Mobile: +81 90-1234-5678
Office: +81 3-5678-1234
Fax: +81 3-5678-1235

住所:
〒100-0001
東京都千代田区千代田1-1-1
ビジネスタワー10階

Business hours: 9:00-18:00 JST (Japan Standard Time)
Languages: Japanese (native), English (business level), Mandarin Chinese (conversational)

LinkedIn: linkedin.com/in/tanaka-taro
WeChat ID: tanaka_taro_2024
"""

expected_json = """{
  "name": {
    "full_name": "田中 太郎 (Tanaka Taro)",
    "first_name": "Taro",
    "last_name": "Tanaka"
  },
  "job_title": "アジア太平洋地域マネージャー",
  "company": {
    "name": "グローバルテック株式会社"
  },
  "email_addresses": [
    {
      "email": "t.tanaka@globaltech.co.jp",
      "type": "work",
      "primary": true
    },
    {
      "email": "taro.tanaka@example.com",
      "type": "personal"
    }
  ],
  "phone_numbers": [
    {
      "number": "+81 90-1234-5678",
      "type": "mobile",
      "primary": true
    },
    {
      "number": "+81 3-5678-1234",
      "type": "work"
    },
    {
      "number": "+81 3-5678-1235",
      "type": "fax"
    }
  ],
  "addresses": [
    {
      "type": "work",
      "street": "千代田区千代田1-1-1, ビジネスタワー10階",
      "city": "東京都",
      "postal_code": "100-0001",
      "country": "Japan",
      "full_address": "〒100-0001 東京都千代田区千代田1-1-1 ビジネスタワー10階"
    }
  ],
  "social_media": {
    "linkedin": "linkedin.com/in/tanaka-taro",
    "other": [
      {
        "platform": "WeChat",
        "handle": "tanaka_taro_2024"
      }
    ]
  },
  "timezone": "JST",
  "language": "Japanese"
}"""
