input_text = """
John Smith
john.smith@email.com
"""

expected_json = """{
  "name": {
    "full_name": "John Smith",
    "first_name": "John",
    "last_name": "Smith"
  },
  "email_addresses": [
    {
      "email": "john.smith@email.com",
      "primary": true
    }
  ]
}"""
